### ISSUE TITLE
Installation will not work

### ISSUE THREAD

**Issue by tehmilcho** [denniss17/pimatic-angular-material-frontend#7]
Hey 

i try to install your Plugin but its not working, i only get a blank Page if i go to the Mounting Point.

In the browser console are follow errors .. 

GET http://leetwerkberry:1337/ma/bower_components/socket.io-client/socket.io.js 
GET http://leetwerkberry:1337/ma/bower_components/socket.io-client/socket.io.js 404 (Not Found)
Uncaught ReferenceError: io is not defined(…)

![browser](https://cloud.githubusercontent.com/assets/22918349/20651352/e2eff7f0-b4e3-11e6-9909-eed50c85e519.JPG)

i tried the installation over the Pimatic GUI and over your Guide, both do not work =/

**Comment by dennisschroer** [comment]
Hey,

Can you check if the `bower_components` directory exists and the given file exists in your project? In your pimatic application, it should be in `node_modules/pimatic-angular-material-frontend/bower_components`.

If not, it could be that the installation failed because of bower failing to install. Try to do:

    > cd node_modules/pimatic-angular-material-frontend
    > bower install

Please let me know if this works, and if any error occurs I would like to know which error. Thanks!

**Comment by tehmilcho** [comment]
Hey,

the folder is there with 19,6MB and 741 Files but under "home\pi\pimatic-app\node_modules\pimatic\angular-material-frontend\bower_components\socket.io-client" the "socket.io.js" is missing

I tried ">bower install" frist it says he dont know "bower", so i installed "bower" global, than i tryed it againg. A file is missing in "uv_cwd"

![bower](https://cloud.githubusercontent.com/assets/22918349/20659463/0f9a8206-b544-11e6-8a89-b6e21990e167.PNG)

**Comment by tehmilcho** [comment]
Okay this Bower message comes only if you have 2 Consoles with Bower open, i closed all Consoles, reinstalled the Plugin, run agian bower install, no message .. but no change .. same blank Page.

Will this Plugin use a Port? maybe 8080 or something like that?

**Comment by dennisschroer** [comment]
Do you also get this error when running `npm -v`?: https://github.com/npm/npm/issues/10983

Bower install was succesful after closing the consoles? Or did you still get the same console error?

The plugin does not open an additional port, it uses the same port already used by pimatic.

**Comment by tehmilcho** [comment]
Yes i can run everthing without a Error. 

![node](https://cloud.githubusercontent.com/assets/22918349/20680224/717e05d8-b59e-11e6-9841-938e6722bccc.jpg)

**Comment by dennisschroer** [comment]
And removing bower_components and reinstalling?

**Comment by tehmilcho** [comment]
I deinstall the plugin about 5x times .. the folder will be removed but its everytime the same Error.

**Comment by tehmilcho** [comment]
pi@Leetwerkberry:~/pimatic-app/node_modules/pimatic-angular-material-frontend $ bower install
bower cached        https://github.com/angular/bower-angular.git#1.5.9
bower validate      1.5.9 against https://github.com/angular/bower-angular.git#^1.5.5
bower cached        https://github.com/angular/bower-material.git#1.1.1
bower validate      1.1.1 against https://github.com/angular/bower-material.git#^1.0.7
bower cached        https://github.com/angular/bower-angular-messages.git#1.5.9
bower validate      1.5.9 against https://github.com/angular/bower-angular-messages.git#^1.5.5
bower cached        https://github.com/angular/bower-angular-route.git#1.5.9
bower validate      1.5.9 against https://github.com/angular/bower-angular-route.git#^1.5.5
bower cached        https://github.com/PascalPrecht/bower-angular-translate.git#2.11.1
bower validate      2.11.1 against https://github.com/PascalPrecht/bower-angular-translate.git#~2.11.0
bower cached        https://github.com/Templarian/MaterialDesign-Webfont.git#1.7.22
bower validate      1.7.22 against https://github.com/Templarian/MaterialDesign-Webfont.git#^1.5.54
bower cached        https://github.com/LearnBoost/socket.io-client.git#1.7.1
bower validate      1.7.1 against https://github.com/LearnBoost/socket.io-client.git#~1
bower cached        https://github.com/angular/bower-angular-mocks.git#1.5.9
bower validate      1.5.9 against https://github.com/angular/bower-angular-mocks.git#^1.5.3
bower cached        https://github.com/angular/bower-angular.git#1.5.9
bower validate      1.5.9 against https://github.com/angular/bower-angular.git#>=1.2.26 <1.6
bower cached        https://github.com/angular/bower-angular-animate.git#1.5.9
bower validate      1.5.9 against https://github.com/angular/bower-angular-animate.git#^1.4.8
bower cached        https://github.com/angular/bower-angular-aria.git#1.5.9
bower validate      1.5.9 against https://github.com/angular/bower-angular-aria.git#^1.4.8
bower install       angular-translate#2.11.1
bower install       angular#1.5.9
bower install       socket.io-client#1.7.1
bower install       mdi#1.7.22
bower install       angular-messages#1.5.9
bower install       angular-material#1.1.1
bower install       angular-route#1.5.9
bower install       angular-mocks#1.5.9
bower install       angular-aria#1.5.9
bower install       angular-animate#1.5.9

angular-translate#2.11.1 bower_components/angular-translate
└── angular#1.5.9

angular#1.5.9 bower_components/angular

socket.io-client#1.7.1 bower_components/socket.io-client

mdi#1.7.22 bower_components/mdi

angular-messages#1.5.9 bower_components/angular-messages
└── angular#1.5.9

angular-material#1.1.1 bower_components/angular-material
├── angular#1.5.9
├── angular-animate#1.5.9
├── angular-aria#1.5.9
└── angular-messages#1.5.9

angular-route#1.5.9 bower_components/angular-route
└── angular#1.5.9

angular-mocks#1.5.9 bower_components/angular-mocks
└── angular#1.5.9

angular-aria#1.5.9 bower_components/angular-aria
└── angular#1.5.9

angular-animate#1.5.9 bower_components/angular-animate
└── angular#1.5.9
pi@Leetwerkberry:~/pimatic-app/node_modules/pimatic-angular-material-frontend $  

*** Update full log ***

**Comment by kaedwen** [comment]
Same Problem here
socket.io.js not found in Browser

But it is on the filesystem

> bower_components/socket.io-client/
├── dist
│   ├── socket.io.js
│   ├── socket.io.js.map
│   ├── socket.io.min.js
│   ├── socket.io.slim.js
│   ├── socket.io.slim.js.map
│   └── socket.io.slim.min.js
├── gulpfile.js
├── History.md
├── lib
│   ├── index.js
│   ├── manager.js
│   ├── on.js
│   ├── socket.js
│   └── url.js
├── LICENSE
├── Makefile
├── package.json
├── README.md
├── support
│   ├── noop.js
│   ├── webpack.config.js
│   └── webpack.config.slim.js
├── test
│   ├── connection.js
│   ├── index.js
│   ├── socket.js
│   ├── support
│   │   ├── env.js
│   │   └── server.js
│   └── url.js
└── zuul.config.js

**Comment by tehmilcho** [comment]
no more idears to fix? =(

**Comment by dennisschroer** [comment]
It seems like the repo of socket.io is updated, where the `socket.io.js` file is now in the `dist` folder instead of in the root (as can be seen in https://github.com/denniss17/pimatic-angular-material-frontend/issues/7#issuecomment-264003341). Let me check it, if it is indeed the case I will update it.

**Comment by dennisschroer** [comment]
Such a simple solution for this issue: It was indeed an update of socket.io, since version 1.70 they put everything in `dist`.

Fixed in https://github.com/denniss17/pimatic-angular-material-frontend/pull/8
